Repository nextcloud/tables, pull requests merged in 2023-05, with the labels that each got.

#301 fix(search): enables non case sensitive search
  cypress/e2e/tables.cy.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeDateMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeTimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberProgressMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberStarsMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMultiMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLineMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLinkMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLongMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textRichMixin.js
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: bug, 3. to review

#333 Fix : Translation of table row creation button's label
  src/shared/components/ncTable/NcTable.vue
Labels: bug, 3. to review

#332 Fix : Translation of table column creation button's label
  src/modules/main/sections/EmptyTable.vue
Labels: bug, 3. to review

#330 Fix : Translation call on start page
  src/pages/Startpage.vue
Labels: bug, 3. to review

#315 fix(Options): prevents buttons to get cut off
  src/shared/components/ncTable/partials/SearchForm.vue
  src/shared/components/ncTable/sections/Options.vue
  src/shared/mixins/viewportHelper.js
Labels: 4. to release

#323 fix(EditorMenubar): Renders Rich Editor Menubar behind dropdowns
  src/shared/components/ncEditor/NcEditor.vue
Labels: bug, 4. to release
