Repository nextcloud/tables, pull requests merged in 2023-06, with the labels that each got.

#340 fix(datecell): Date now is no longer shown as invalid date
  src/shared/components/ncTable/partials/TableCellDateTime.vue
Labels: bug, 3. to review

#322 feat(Filtering): Enables to filter for empty cells
  src/shared/components/ncTable/mixins/columnsTypes/datetimeDateMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeTimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberProgressMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMultiMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLineMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLinkMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLongMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textRichMixin.js
  src/shared/components/ncTable/mixins/searchAndFilterMixin.js
  src/shared/components/ncTable/partials/FilterLabel.vue
  src/shared/components/ncTable/partials/TableHeader.vue
  src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: enhancement, 3. to review

#318 fix(RichTextCell): Removed unnecessary padding
  src/shared/components/ncTable/partials/TableCellEditor.vue
Labels: 3. to review

#339 fix(NcMultiselect): Replaces NcMultiselects by NcSelects
  cypress/e2e/tables-share.cy.js
  src/modules/main/partials/ColumnTypeSelection.vue
  src/modules/sidebar/partials/ShareForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/SelectionForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/SelectionMultiForm.vue
Labels: technical debt, 3. to review

#374 chore: update node engines to next LTS
  package.json
Labels: dependencies, 3. to review, automated

#338 refactor: OO approach for better handling of columns and more
  src/modules/main/modals/CreateRow.vue
  src/modules/main/modals/EditRow.vue
  src/modules/main/partials/ColumnFormComponent.vue
  src/pages/DefaultMainView.vue
  src/shared/components/ncTable/mixins/columnClass.js
  src/shared/components/ncTable/mixins/columnHandler.js
  src/shared/components/ncTable/mixins/columnParser.js
  src/shared/components/ncTable/mixins/columnsTypes/datetime.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeDate.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeDateMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeTime.js
  src/shared/components/ncTable/mixins/columnsTypes/datetimeTimeMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/number.js
  src/shared/components/ncTable/mixins/columnsTypes/numberMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js
  src/shared/components/ncTable/mixins/columnsTypes/numberProgressMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/numberStars.js
  src/shared/components/ncTable/mixins/columnsTypes/numberStarsMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selection.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionCheck.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionCheckMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMulti.js
  src/shared/components/ncTable/mixins/columnsTypes/selectionMultiMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLine.js
  src/shared/components/ncTable/mixins/columnsTypes/textLineMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLink.js
  src/shared/components/ncTable/mixins/columnsTypes/textLinkMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textLong.js
  src/shared/components/ncTable/mixins/columnsTypes/textLongMixin.js
  src/shared/components/ncTable/mixins/columnsTypes/textRich.js
  src/shared/components/ncTable/mixins/columnsTypes/textRichMixin.js
  src/shared/components/ncTable/mixins/exportTableMixin.js
  src/shared/components/ncTable/mixins/filter.js
  src/shared/components/ncTable/mixins/magicFields.js
  src/shared/components/ncTable/mixins/searchAndFilterMixin.js
  src/shared/components/ncTable/partials/FilterLabel.vue
  src/shared/components/ncTable/partials/TableCellDateTime.vue
  src/shared/components/ncTable/partials/TableCellMultiSelection.vue
  src/shared/components/ncTable/partials/TableCellSelection.vue
  src/shared/components/ncTable/partials/TableHeader.vue
  src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue
  src/shared/components/ncTable/partials/TableRow.vue
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: 3. to review
