Repository nextcloud/tables, pull requests merged in 2023-08, with the labels that each got.

#446 feat: more gentle icon
  img/app-dark.svg
  img/app.svg
Labels: design, papercut, 3. to review

#456 fix(Permissions, Filter): Adjusts permissions for tables, removes filters for selection columns
  lib/Db/ColumnTypes/SelectionColumnQB.php
  lib/Service/PermissionsService.php
  src/shared/components/ncTable/mixins/filter.js
Labels: bug, 3. to review

#467 fix: Replace creation with connection icon
  src/modules/main/sections/Dashboard.vue
  src/modules/main/sections/DataTable.vue
  src/modules/main/sections/View.vue
  src/modules/navigation/partials/NavigationTableItem.vue
  src/modules/navigation/partials/NavigationViewItem.vue
  src/modules/sidebar/sections/Sidebar.vue
Labels: bug, design, 3. to review

#470 fix: No need to show toast messages on success
  cypress/e2e/tables-share.cy.js
  src/modules/sidebar/mixins/shareAPI.js
Labels: bug, 3. to review

#466 Avoid error on CORS requests
  lib/Controller/Api1Controller.php
Labels: bug, 2. developing, feedback-requested

#506 fix: Make sure to have a local value before initializing the editor
  src/shared/components/ncEditor/NcEditor.vue
Labels: bug, 3. to review

#505 fix: Select tile on enter
  src/shared/components/NcTile/NcTile.vue
Labels: bug, 3. to review
