Repository nextcloud/tables, pull requests merged in 2024-03, with the labels that each got.

#885 fix(Permissions): check against user provided in args
  lib/Service/PermissionsService.php
Labels: bug, 3. to review

#865 feat: Add backend for table archive and favorite flag
  appinfo/routes.php
  composer.json
  lib/Capabilities.php
  lib/Command/RenameTable.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiFavoriteController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/TableController.php
  lib/Db/Table.php
  lib/Db/View.php
  lib/Migration/Version000800Date20240222000000.php
  lib/ResponseDefinitions.php
  lib/Service/FavoritesService.php
  lib/Service/TableService.php
  lib/Service/ViewService.php
  src/modules/navigation/partials/NavigationTableItem.vue
  src/modules/navigation/partials/NavigationViewItem.vue
  src/modules/navigation/sections/Navigation.vue
  src/shared/constants.js
  src/store/store.js
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: enhancement, 2. developing

#883 Polish table header and text column rendering
  src/shared/components/ncTable/partials/TableCellEditor.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/shared/components/ncTable/sections/Options.vue
Labels: bug, design, 3. to review

#901 cypress testing for archive/favorite
  cypress/e2e/tables-archive.cy.js
  cypress/e2e/tables-favorite.cy.js
Labels: tests

#900 Match default values when querying views
  lib/Db/Column.php
  lib/Db/Row2Mapper.php
Labels: bug, 3. to review

#909 fix: properly indent child views of archived tables
  src/modules/navigation/sections/Navigation.vue
Labels: bug, design, 3. to review

#890 Feat: File action to import from Files to Tables
  .github/workflows/cypress.yml
  cypress/e2e/tables-import.cy.js
  lib/AppInfo/Application.php
  lib/Listener/LoadAdditionalListener.php
  package-lock.json
  package.json
  src/file-actions.js
  src/modules/modals/FileActionImport.vue
  src/modules/modals/Import.vue
  src/modules/modals/ImportResults.vue
  webpack.js
Labels: enhancement, 4. to release

#913 chore(release): Bump version to 0.7.0-beta.2
  CHANGELOG.md
  appinfo/info.xml
  lib/Listener/LoadAdditionalListener.php
  package.json
Labels: 3. to review

#919 fix(OpenApi): resolve errors and generate openapi file
  .github/workflows/openapi.yml
  composer.json
  lib/Controller/Api1Controller.php
  lib/Controller/ApiFavoriteController.php
  lib/Controller/ApiTablesController.php
  openapi.json
  package-lock.json
  package.json
  src/types/openapi/openapi.ts
  tsconfig.json
Labels: 4. to release

#861 Contexts API
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Command/ListContexts.php
  lib/Command/ShowContext.php
  lib/Controller/AOCSController.php
  lib/Controller/ContextController.php
  lib/Db/Context.php
  lib/Db/ContextMapper.php
  lib/Db/ContextNodeRelation.php
  lib/Db/ContextNodeRelationMapper.php
  lib/Db/Page.php
  lib/Db/PageContent.php
  lib/Db/PageContentMapper.php
  lib/Db/PageMapper.php
  lib/Errors/BadRequestError.php
  lib/Middleware/PermissionMiddleware.php
  lib/ResponseDefinitions.php
  lib/Service/ContextService.php
  lib/Service/PermissionsService.php
  openapi.json
  psalm.xml
  src/types/openapi/openapi.ts
  tests/unit/Service/PermissionsServiceTest.php
Labels: enhancement, 3. to review

#924 chore: Remove legacy reference provider
  lib/AppInfo/Application.php
  lib/Reference/LegacyReferenceProvider.php
Labels: technical debt, 3. to review

#929 feat: contexts material design icon picker
  img/material/meta.json
  src/modules/modals/CreateContext.vue
  src/modules/modals/EditContext.vue
  src/modules/navigation/partials/NavigationContextItem.vue
  src/pages/Context.vue
  src/shared/components/ncContextResource/ResourceList.vue
  src/shared/components/ncIconPicker/NcIconPicker.vue
  src/shared/components/ncIconPicker/mixins/svgHelper.js
  src/shared/components/ncIconPicker/partials/Icon.vue
  src/shared/components/ncIconPicker/partials/IconPicker.vue
  webpack.js
Labels: enhancement, 3. to review

#904 feat(Contexts): add Contexts to navigation when applicable
  lib/AppInfo/Application.php
  lib/Db/ContextMapper.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Service/ContextService.php
Labels: enhancement, 3. to review

#925 fix: Focus first input when creating a new table/row/column/view
  cypress/e2e/column-selection.cy.js
  src/modules/modals/CreateColumn.vue
  src/modules/modals/CreateRow.vue
  src/modules/modals/CreateTable.vue
  src/modules/modals/ViewSettings.vue
Labels: bug, 3. to review

#916 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress-custom.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm-matrix-custom.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies, 3. to review, automated

#936 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#921 fix: shared views can be favorited
  cypress/e2e/tables-favorite.cy.js
  src/modules/navigation/sections/Navigation.vue
Labels: bug, 3. to review

#943 fix: reintroduce content reference provider
  lib/AppInfo/Application.php
Labels: bug, 3. to review

#951 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#954 fix(api): ContextMapper now coerces the row ID to an int for proper comparison
  lib/Db/ContextMapper.php
Labels: bug, 3. to review
