Repository nextcloud/tables, pull requests merged in 2024-12, with the labels that each got.

#1485 fix: Use devcontainer with php v8.2
  .devcontainer/devcontainer.json
Labels: bug, 3. to review

#1488 enh: use tiptap's editor to render HTML
  src/shared/components/ncTable/partials/TableCellHtml.vue
Labels: enhancement, backport-request, 3. to review

#1445 fix: ensure number progress stays within 1-100 range
  cypress/e2e/column-number-progress.cy.js
  src/shared/components/ncTable/partials/columnTypePartials/forms/NumberProgressForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/NumberProgressForm.vue
Labels: bug, 3. to review

#1443 fix: use actual providerId in link rows
  lib/Service/ColumnTypes/TextLinkBusiness.php
Labels: 3. to review

#1515 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
