Repository nextcloud/tables, pull requests merged in 2024-10, with the labels that each got.

#1406 refactor: Extend Permission Middleware usage and replace deprecated annotations with attributes
  lib/Controller/Api1Controller.php
  lib/Controller/ApiColumnsController.php
  lib/Controller/ApiFavoriteController.php
  lib/Controller/ApiGeneralController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/ColumnController.php
  lib/Controller/ContextController.php
  lib/Controller/ImportController.php
  lib/Controller/PageController.php
  lib/Controller/RowController.php
  lib/Controller/SearchController.php
  lib/Controller/ShareController.php
  lib/Controller/TableController.php
  lib/Controller/TableTemplateController.php
  lib/Controller/ViewController.php
  lib/Middleware/PermissionMiddleware.php
  tests/integration/features/APIv2.feature
Labels: enhancement, backport-request, 3. to review

#1395 [stable0.8] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1411 build(release): 0.8.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1394 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1418 [stable0.8] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1421 fix return status in a few cases and add integration tests against content modification through Applications
  lib/Service/RowService.php
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/CollectionManager.php
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, backport-request, 3. to review, tests

#1383 fix(Import): expect selectionOptions as array from json
  lib/Controller/ApiTablesController.php
Labels: bug, backport-request, 3. to review
