Repository nextcloud/tables, pull requests merged in 2024-06, with the labels that each got.

#1119 test(cypress): fix month names
  cypress/e2e/column-datetimeDate.cy.js
Labels: backport-request, 3. to review, tests

#1112 feat: submit row details with ctrl + enter
  src/modules/modals/CreateRow.vue
  src/modules/modals/EditRow.vue
Labels: enhancement, 3. to review

#1072 ci(integration): tests against context updates
  lib/Controller/ContextController.php
  lib/Service/ContextService.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: backport-request, 3. to review

#1117 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1078 add table_id index to oc_tables_columns
  lib/AppInfo/Application.php
  lib/Listener/AddMissingIndicesListener.php
  lib/Migration/Version000000Date20210921000000.php
  lib/Migration/Version000700Date20230916000000.php
  lib/Service/ColumnService.php
Labels: enhancement, 3. to review, performance

#1124 test(integration): cases against context transfer ownership
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 3. to review

#1129 ci(integration): test against context sharing
  lib/Controller/Api1Controller.php
  lib/Controller/ShareController.php
  lib/Middleware/Attribute/RequirePermission.php
  lib/Middleware/PermissionMiddleware.php
  lib/Service/PermissionsService.php
  lib/Service/ShareService.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/integration/features/APIv1.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: enhancement, backport-request, 3. to review

#1130 fix(Controller): remove unneeded endpoints
  appinfo/routes.php
  lib/Controller/ContextController.php
  openapi.json
  src/types/openapi/openapi.ts
Labels: bug, backport-request, technical debt, 3. to review

#1134 build(release): 0.7.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1116 chore(deps): Update openapi-extractor
  openapi.json
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.lock
Labels: dependencies, 3. to review, feature: api

#1136 fix(View): 'manageTable' array key is not always set
  lib/Db/View.php
  lib/Service/ViewService.php
Labels: bug, 3. to review

#1137 ci(integration): add more share-related tests
  tests/integration/features/APIv2.feature
Labels: 3. to review, tests

#1145 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1151 fix: hide Create Column button on empty table if inadequate permissions
  src/modules/main/sections/EmptyTable.vue
Labels: bug, 3. to review

#1148 fix: add aria-label to NcSelect
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: bug, 3. to review

#1147 fix: pass view as prop to EmptyView
  src/modules/main/sections/EmptyView.vue
  src/modules/main/sections/View.vue
Labels: enhancement, 3. to review

#1165 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1169 fix(API): declared array shape was not correct
  lib/Controller/Api1Controller.php
  openapi.json
  src/types/openapi/openapi.ts
Labels: bug, 3. to review

#1161 enh(API): add OCS API to create rows
  appinfo/routes.php
  lib/Controller/RowOCSController.php
  lib/Helper/ConversionHelper.php
  lib/Middleware/PermissionMiddleware.php
  lib/Model/Permissions.php
  lib/Model/RowDataInput.php
  lib/Service/PermissionsService.php
  lib/Service/RowService.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/run.sh
Labels: enhancement, 3. to review

#1025 enh: Consolidate user/group search code
  cypress/e2e/tables-table.cy.js
  src/modules/modals/EditContext.vue
  src/modules/modals/TransferContext.vue
  src/modules/modals/TransferTable.vue
  src/modules/sidebar/partials/ShareForm.vue
  src/shared/components/ncContextResource/ResourceSharees.vue
  src/shared/components/ncUserPicker/NcUserPicker.vue
  src/shared/mixins/searchUserGroup.js
  src/store/store.js
Labels: 3. to review, feedback-requested
