Repository nextcloud/tables, pull requests merged in 2024-04, with the labels that each got.

#958 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#960 feat: add vertical column lines to Tables
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: bug, 3. to review

#964 fix(Contexts): explicitely state non-int types
  lib/Db/Context.php
  lib/Db/ContextMapper.php
  lib/Db/ContextNodeRelation.php
  lib/Db/PageContent.php
Labels: bug, 4. to release

#969 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#978 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#959 feat: Write critical operations to the audit log
  lib/AppInfo/Application.php
  lib/Db/LegacyRowMapper.php
  lib/Db/RowCellSuper.php
  lib/Event/RowDeletedEvent.php
  lib/Event/TableDeletedEvent.php
  lib/Event/TableOwnershipTransferredEvent.php
  lib/Event/ViewDeletedEvent.php
  lib/Listener/WhenRowDeletedAuditLogListener.php
  lib/Listener/WhenTableDeletedAuditLogListener.php
  lib/Listener/WhenTableTransferredAuditLogListener.php
  lib/Listener/WhenViewDeletedAuditLogListener.php
  lib/Service/RowService.php
  lib/Service/Support/AuditLogServiceInterface.php
  lib/Service/Support/DefaultAuditLogService.php
  lib/Service/TableService.php
  lib/Service/ViewService.php
  tests/unit/Listener/WhenRowDeletedAuditLogTest.php
  tests/unit/Listener/WhenTableDeletedAuditLogTest.php
  tests/unit/Listener/WhenTableOwnerTransferredAuditLogTest.php
  tests/unit/Listener/WhenViewDeletedAuditLogTest.php
  tests/unit/Service/Support/DefaultAuditLogServiceTest.php
Labels: 2. developing, feedback-requested

#961 enh: some design review tasks
  src/modules/modals/CreateContext.vue
  src/modules/modals/EditContext.vue
  src/pages/Context.vue
Labels: feedback-requested

#932 Feat/54 add an introduction textarea
  cypress/e2e/tables-archive.cy.js
  cypress/e2e/tables-table.cy.js
  lib/Command/RenameTable.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiTablesController.php
  lib/Controller/TableController.php
  lib/Db/Table.php
  lib/Migration/Version000000Date20210921000000.php
  lib/Migration/Version000900Date20240314000000.php
  lib/Service/TableService.php
  openapi.json
  src/modules/main/sections/ElementTitle.vue
  src/modules/main/sections/Table.vue
  src/modules/main/sections/TableDescription.vue
  src/modules/main/sections/TableWrapper.vue
  src/modules/main/sections/View.vue
  src/modules/modals/CreateTable.vue
  src/modules/modals/EditTable.vue
  src/store/store.js
  src/types/openapi/openapi.ts
Labels: enhancement, 4. to release

#962 feat(Context): add share logic for contexts
  appinfo/routes.php
  lib/Controller/Api1Controller.php
  lib/Controller/ShareController.php
  lib/Db/ContextMapper.php
  lib/Db/ContextNavigation.php
  lib/Db/ContextNavigationMapper.php
  lib/ResponseDefinitions.php
  lib/Service/ContextService.php
  lib/Service/PermissionsService.php
  lib/Service/ShareService.php
  lib/Service/TableService.php
  lib/Service/ViewService.php
  openapi.json
  src/modules/modals/CreateContext.vue
  src/modules/modals/EditContext.vue
  src/pages/Context.vue
  src/shared/components/ncContextResource/NcContextResource.vue
  src/shared/components/ncContextResource/ResourceForm.vue
  src/shared/components/ncContextResource/ResourceSharePermissions.vue
  src/shared/components/ncContextResource/ResourceSharees.vue
  src/shared/components/ncContextResource/mixins/permissionBitmask.js
  src/shared/constants.js
  src/store/store.js
  src/types/openapi/openapi.ts
  tests/integration/features/bootstrap/FeatureContext.php
Labels: 4. to release

#915 feat: create new table from import
  cypress/e2e/tables-table.cy.js
  src/modules/modals/CreateTable.vue
Labels: enhancement, 3. to review

#1001 fix: Properly set random icon on load
  src/modules/modals/CreateContext.vue
Labels: bug, 3. to review

#1010 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#1023 fix(filter): pass datetime object for PARAM_DATE
  lib/Db/Row2Mapper.php
Labels: bug, backport-request, 3. to review

#1002 Fix filters for meta columns
  lib/Db/Column.php
  lib/Db/ColumnMapper.php
  lib/Db/ColumnTypes/SuperColumnQB.php
  lib/Db/Row2Mapper.php
  lib/Service/TableTemplateService.php
  src/shared/components/ncTable/mixins/exportTableMixin.js
  src/shared/components/ncTable/partials/TableRow.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/shared/constants.js
Labels: bug, backport-request, 3. to review

#970 test(Integration): add contexts related tests
  lib/Controller/ContextController.php
  lib/Service/ContextService.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/CollectionManager.php
  tests/integration/features/bootstrap/FeatureContext.php
Labels: backport-request, 3. to review

#1032 chore(release): Bump version to 0.7.1
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: backport-request
