Repository nextcloud/tables, pull requests merged in 2024-07, with the labels that each got.

#877 Extract selection option labels for Analytics
  lib/Analytics/AnalyticsDatasource.php
  lib/Listener/AnalyticsDatasourceListener.php
  tests/stub.phpstub
Labels: bug, 4. to release

#1179 chore: Drop Nextcloud 26 for the next release as it is EOL
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  appinfo/info.xml
  cypress/e2e/tables-import.cy.js
  lib/Controller/RowOCSController.php
  lib/Middleware/PermissionMiddleware.php
Labels: 3. to review

#1178 fix: modify context nodes update
  cypress/e2e/context.cy.js
  cypress/support/commands.js
  lib/Controller/ContextController.php
  src/modules/modals/CreateContext.vue
  src/modules/modals/DeleteContext.vue
  src/modules/modals/EditContext.vue
  src/modules/modals/TransferContext.vue
  src/modules/navigation/partials/NavigationContextItem.vue
  src/modules/navigation/sections/Navigation.vue
  src/shared/components/ncContextResource/NcContextResource.vue
  src/shared/components/ncContextResource/ResourceSharePermissions.vue
  src/shared/components/ncTable/NcTable.vue
Labels: 3. to review

#1173 fix(Backend): use object over loose array for permissions
  lib/Db/Table.php
  lib/Db/View.php
  lib/Model/Permissions.php
  lib/ResponseDefinitions.php
  lib/Service/PermissionsService.php
  lib/Service/ShareService.php
  lib/Service/TableService.php
  lib/Service/ViewService.php
Labels: bug, 4. to release

#1205 fix(api): Fix wrong array type
  lib/Controller/Api1Controller.php
  lib/Controller/RowOCSController.php
  openapi.json
  src/types/openapi/openapi.ts
Labels: bug, 3. to review

#1204 fix: flaky Cypress tests
  cypress/e2e/context.cy.js
  cypress/e2e/tables-import.cy.js
  cypress/e2e/tables-rows.cy.js
  cypress/e2e/tables-share.cy.js
  cypress/e2e/tables-table.cy.js
  cypress/support/commands.js
  src/modules/modals/CreateTable.vue
  src/modules/navigation/sections/Navigation.vue
Labels: 3. to review

#1199 fix: remove View filter with null column
  src/modules/modals/ViewSettings.vue
Labels: bug

#1209 [stable0.7] fix(api): Fix wrong array type
  lib/Controller/Api1Controller.php
  openapi.json
  src/types/openapi/openapi.ts
Labels: bug, 3. to review

#1215 fix(Capabilities): announce API 2.0
  lib/Capabilities.php
  lib/Controller/ContextController.php
  openapi.json
Labels: backport-request, 3. to review

#1218 fix(files): remove pagination of there is just one page
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: 3. to review

#1221 build(openapi): fix ms typescript generation command
  package.json
  src/types/openapi/openapi.ts
Labels: 4. to release, feature: api

#1227 [stable0.7] fix(ViewService): treat missing index manageTable pragmatically
  lib/Service/ViewService.php
Labels: bug, 3. to review

#1196 fix(View): column might be saved as null
  lib/Db/View.php
Labels: bug, backport-request, 4. to release

#1220 fix(files): fix width, background of table row and interval between table header
  src/modules/main/sections/ElementTitle.vue
  src/shared/components/ncTable/NcTable.vue
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: 3. to review

#944 feat(import): change column format during import
  appinfo/routes.php
  cypress/e2e/tables-import.cy.js
  cypress/e2e/tables-table.cy.js
  lib/Controller/ImportController.php
  lib/Service/ColumnService.php
  lib/Service/ImportService.php
  src/App.vue
  src/modules/main/partials/ColumnTypeSelection.vue
  src/modules/modals/CreateColumn.vue
  src/modules/modals/Import.vue
  src/modules/modals/ImportPreview.vue
  src/modules/modals/Modals.vue
Labels: enhancement, 3. to review

#1170 add scheme import and export
  appinfo/routes.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiTablesController.php
  lib/Controller/TableScheme.php
  lib/Db/Table.php
  lib/Service/TableService.php
  openapi.json
  src/modules/modals/CreateTable.vue
  src/modules/modals/ImportScheme.vue
  src/modules/modals/Modals.vue
  src/modules/navigation/partials/NavigationTableItem.vue
  src/types/openapi/openapi.ts
Labels: enhancement, 2. developing

#1240 Align button to the left side
  src/modules/modals/EditRow.vue
Labels: 3. to review

#1219 fix(files): align icon to center
  src/modules/modals/CreateContext.vue
  src/modules/modals/CreateTable.vue
  src/modules/modals/EditTable.vue
Labels: 2. developing

#1234 fix(files): remove unneeded extra place for the rows
  src/shared/components/ncTable/sections/CustomTable.vue
Labels: 3. to review

#1241 chore: bump stable0.7 to version 0.7.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1244 fix(files): fix appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#1090 feat: add backend for new user/group column
  appinfo/routes.php
  lib/Capabilities.php
  lib/Controller/AOCSController.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiColumnsController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/ColumnController.php
  lib/Db/Column.php
  lib/Db/ColumnTypes/UsergroupColumnQB.php
  lib/Db/Row2Mapper.php
  lib/Db/RowCellDatetime.php
  lib/Db/RowCellMapperSuper.php
  lib/Db/RowCellNumber.php
  lib/Db/RowCellNumberMapper.php
  lib/Db/RowCellSelection.php
  lib/Db/RowCellSelectionMapper.php
  lib/Db/RowCellSuper.php
  lib/Db/RowCellText.php
  lib/Db/RowCellUsergroup.php
  lib/Db/RowCellUsergroupMapper.php
  lib/Helper/ColumnsHelper.php
  lib/Migration/Version000000Date20210921000000.php
  lib/Migration/Version000800Date20240712000000.php
  lib/ResponseDefinitions.php
  lib/Service/ColumnService.php
  lib/Service/ColumnTypes/IColumnTypeBusiness.php
  lib/Service/ColumnTypes/UsergroupBusiness.php
  lib/Service/ImportService.php
  lib/Service/RowService.php
  lib/Service/TableTemplateService.php
  openapi.json
  src/types/openapi/openapi.ts
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/run.sh
Labels: feedback-requested, 🍂 2024-Autumn
