Repository nextcloud/tables, pull requests merged in 2024-01, with the labels that each got.

#753 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: dependencies, 3. to review, automated

#755 feat: add error hints for mandatory fields
  cypress/e2e/tables-rows.cy.js
  src/modules/modals/CreateRow.vue
  src/modules/modals/EditRow.vue
Labels: enhancement, 3. to review

#760 fix: increase smartpicker select height
  src/views/partials/SearchAndSelectOption.vue
  src/views/sections/Search.vue
Labels: 3. to review

#741 feat: transfer ownership via webgui
  appinfo/routes.php
  composer.lock
  cypress/e2e/tables-table.cy.js
  lib/Command/ChangeOwnershipTable.php
  lib/Controller/ApiTablesController.php
  lib/Service/PermissionsService.php
  lib/Service/TableService.php
  openapi.json
  src/modules/modals/EditTable.vue
  src/modules/modals/Modals.vue
  src/modules/modals/TransferTable.vue
  src/modules/sidebar/partials/ShareForm.vue
  src/shared/components/ncTable/mixins/columnClass.js
  src/shared/components/ncTable/mixins/permissionsMixin.js
  src/shared/components/ncUserAndGroupPicker/NcUserAndGroupPicker.vue
  src/shared/mixins/shareTypesMixin.js
  src/store/store.js
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: enhancement, 3. to review, feedback-requested

#774 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#776 Update npm and node engines versions
  package.json
Labels: dependencies

#779 Avoid failures with link column database values from previous versions
  lib/Service/ColumnTypes/TextLinkBusiness.php
  src/shared/components/ncTable/partials/rowTypePartials/TextLinkForm.vue
  tests/unit/Service/ColumnTypes/TextLinkBusinessTest.php
Labels: bug, backport-request, 3. to review

#783 Create appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#785 [stable0.6] fix: add display names to all column meta data printouts
  lib/Db/Column.php
  lib/Service/ColumnService.php
  src/modules/main/partials/ColumnInfoPopover.vue
  src/modules/modals/EditColumn.vue
  src/shared/components/ncTable/mixins/columnClass.js
Labels: bug, 3. to review

#784 [stable0.6] Fix number column issues
  lib/Service/ColumnService.php
  lib/Service/ColumnTypes/NumberBusiness.php
  src/modules/modals/EditColumn.vue
  src/shared/components/ncTable/mixins/columnClass.js
  src/shared/components/ncTable/mixins/columnsTypes/number.js
  src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js
  src/shared/components/ncTable/mixins/columnsTypes/selection.js
  src/shared/components/ncTable/partials/TableCellNumber.vue
  src/shared/components/ncTable/partials/TableRow.vue
  src/shared/components/ncTable/partials/columnTypePartials/forms/NumberForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/NumberForm.vue
Labels: bug, 3. to review
