Repository nextcloud/tables, pull requests merged in 2024-09, with the labels that each got.

#1334 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1335 [stable0.7] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1337 chore(CI): Updating renovate-approve-merge.yml workflow from template
  .github/workflows/renovate-approve-merge.yml
Labels: dependencies

#1338 fix: check sorting array is non-empty
  src/shared/components/ncTable/mixins/columnClass.js
Labels: 3. to review

#1281 fix: reduce arguments for column creation function
  lib/Controller/Api1Controller.php
  lib/Controller/ApiColumnsController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/ColumnController.php
  lib/Db/Column.php
  lib/Dto/Column.php
  lib/Service/ColumnService.php
  lib/Service/ImportService.php
  lib/Service/TableTemplateService.php
Labels: technical debt, 3. to review

#1351 refactor(Rows): switch front-end to use Row OCS API
  appinfo/routes.php
  lib/Controller/Api1Controller.php
  lib/Controller/Errors.php
  lib/Controller/ImportController.php
  lib/Controller/RowController.php
  lib/Model/RowDataInput.php
  lib/Service/ImportService.php
  lib/Service/RowService.php
  lib/Service/ViewService.php
  openapi.json
  src/modules/modals/CreateRow.vue
  src/store/data.js
  src/types/openapi/openapi.ts
  tests/integration/features/APIv1.feature
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, enhancement, 3. to review

#1311 feat: share Application with groups
  src/modules/modals/EditContext.vue
  src/shared/components/ncContextResource/NcContextResource.vue
  src/shared/components/ncContextResource/ResourceSharees.vue
Labels: enhancement, 3. to review

#1357 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
