Repository nextcloud/tables, pull requests merged in 2024-05, with the labels that each got.

#1037 enh(Contexts): set active navigation entry
  src/App.vue
Labels: enhancement, 3. to review

#1062 perf: Avoid extra queries to get the view ownership
  lib/Db/View.php
  lib/Db/ViewMapper.php
Labels: bug, 3. to review, performance

#1063 perf: Make cache usable for unfavorited entries
  lib/Service/FavoritesService.php
Labels: bug, 3. to review, performance

#1049 fix(DB): update tables_row_sleeves' sequence after migration
  appinfo/info.xml
  lib/Migration/DbRowSleeveSequence.php
  psalm.xml
Labels: bug, backport-request, 3. to review

#1026 enh: Delete Application and its shares
  lib/Db/ContextNodeRelationMapper.php
  lib/Db/PageContentMapper.php
  lib/Db/PageMapper.php
  lib/Service/ContextService.php
  lib/Service/ShareService.php
  src/modules/modals/CreateContext.vue
  src/modules/modals/DeleteContext.vue
  src/modules/modals/EditContext.vue
  src/modules/modals/Modals.vue
  src/modules/navigation/partials/NavigationContextItem.vue
  src/shared/components/ncTable/mixins/permissionsMixin.js
  src/store/store.js
Labels: bug, backport-request, 3. to review

#1042 ci(integration): tests against context deletion
  lib/Middleware/PermissionMiddleware.php
  tests/integration/features/APIv2.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: backport-request, 3. to review

#1077 build(release): 0.7.2
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review

#1080 enh(App): navigation tweaks for Contexts
  appinfo/routes.php
  lib/Controller/PageController.php
  lib/Listener/BeforeTemplateRenderedListener.php
  package-lock.json
  package.json
  src/App.vue
  src/modules/navigation/sections/Navigation.vue
Labels: enhancement, 3. to review

#1083 fix(DB): fetch pageId as int
  lib/Db/PageMapper.php
Labels: bug, 3. to review

#1091 feat: update error handling during import
  lib/Controller/ImportController.php
  src/modules/modals/Import.vue
Labels: 3. to review

#1098 fix: reduce templates requests
  src/App.vue
  src/modules/modals/CreateTable.vue
  src/store/store.js
Labels: bug, 3. to review
