Repository nextcloud/tables, pull requests merged in 2024-08, with the labels that each got.

#1195 fix: Navigation table entries UI issues
  src/modules/navigation/partials/NavigationTableItem.vue
  src/modules/navigation/partials/NavigationViewItem.vue
Labels: bug, 2. developing

#1113 feat: User/group column frontend
  cypress/e2e/column-usergroup.cy.js
  cypress/support/commands.js
  src/modules/main/partials/ColumnFormComponent.vue
  src/modules/main/partials/ColumnTypeSelection.vue
  src/modules/modals/CreateColumn.vue
  src/modules/modals/EditColumn.vue
  src/shared/components/ncTable/mixins/columnClass.js
  src/shared/components/ncTable/mixins/columnHandler.js
  src/shared/components/ncTable/mixins/columnParser.js
  src/shared/components/ncTable/mixins/columnsTypes/usergroup.js
  src/shared/components/ncTable/mixins/filter.js
  src/shared/components/ncTable/partials/TableCellUsergroup.vue
  src/shared/components/ncTable/partials/TableRow.vue
  src/shared/components/ncTable/partials/columnTypePartials/forms/MainForm.vue
  src/shared/components/ncTable/partials/columnTypePartials/forms/UsergroupForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/UsergroupForm.vue
  src/shared/constants.js
  src/store/data.js
Labels: enhancement, 3. to review, 🍂 2024-Autumn

#1254 fix: Make user listing in table more consistent by using NcUserBubble
  cypress/e2e/column-usergroup.cy.js
  src/shared/components/ncTable/partials/TableCellUsergroup.vue
  src/shared/components/ncTable/partials/rowTypePartials/UsergroupForm.vue
Labels: bug, 3. to review

#1260 Prepare for release v0.8.0-beta.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1259 fix/ui quirks
  src/App.vue
  src/modules/modals/CreateTable.vue
  src/modules/navigation/sections/Navigation.vue
  src/modules/sidebar/partials/ShareForm.vue
  src/modules/sidebar/partials/ShareList.vue
  src/modules/sidebar/sections/Sidebar.vue
  src/modules/sidebar/sections/SidebarIntegration.vue
  src/store/store.js
Labels: bug, 3. to review

#1274 fix: Avoid variable access on unhandled exception and lower log level for expected permission check failures
  lib/Service/PermissionsService.php
  lib/Service/ViewService.php
Labels: bug

#1176 fix: ensure default values show as filled
  src/modules/modals/CreateRow.vue
  src/modules/modals/EditRow.vue
  src/shared/components/ncTable/mixins/rowHelper.js
Labels: 2. developing

#1277 Add reuse compliance - Part 1
  .devcontainer/setup.sh
  .eslintrc.js
  .gitattributes
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/command-rebase.yml
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
  .github/workflows/psalm-matrix-custom.yml
  .gitignore
  .l10nignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  REUSE.toml
  appinfo/info.xml
  babel.config.js
  cypress.config.js
  krankerl.toml
  phpunit.integration.xml
  phpunit.xml
  psalm.xml
  tests/phpcs.xml
  tests/psalm-baseline.xml
  webpack.config.js
Labels: technical debt, 3. to review

#1217 chore: Proper logs with error level and exception trace
  lib/Controller/AOCSController.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiGeneralController.php
  lib/Controller/Errors.php
Labels: bug, 3. to review

#1279 Add SPDX header - Part 2
  .github/ISSUE_TEMPLATE/bug-report.yml.license
  .github/ISSUE_TEMPLATE/feature-request.yml.license
  .scripts/release.sh
  LICENSES/CC-BY-SA-2.0.txt
  LICENSES/LicenseRef-AppleAppStoreBadge.txt
  LICENSES/LicenseRef-FacebookTrademarks.txt
  LICENSES/LicenseRef-GooglePlayBadge.txt
  LICENSES/LicenseRef-MastodonTrademarks.txt
  LICENSES/LicenseRef-NextcloudTrademarks.txt
  LICENSES/LicenseRef-XTrademarks.txt
  REUSE.toml
  appinfo/routes.php
  build/fetch-material-icons.sh
  tests/integration/run.sh
Labels: technical debt, 3. to review

#1286 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1292 fix: use different app menu selectors
  src/App.vue
Labels: bug

#1282 fix: only focus on input if modal is open
  src/modules/modals/CreateColumn.vue
  src/modules/modals/CreateRow.vue
Labels: 3. to review

#1301 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1303 chore(deps): Update openapi-extractor to v1.0.0
  openapi.json
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: dependencies, 3. to review

#1310 build(NC): bump max compatible NC version
  appinfo/info.xml
Labels: enhancement, 3. to review

#1312 fix: Open row edit modal on initial load
  src/modules/main/sections/MainWrapper.vue
Labels: bug, 3. to review

#1319 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1239 Migrate `NcModal` to `NcDialog`
  css/modal.css
  cypress/e2e/column-selection-multi.cy.js
  cypress/e2e/column-selection.cy.js
  cypress/e2e/column-text-line.cy.js
  cypress/support/e2e.js
  src/modules/modals/CreateColumn.vue
  src/modules/modals/CreateContext.vue
  src/modules/modals/CreateRow.vue
  src/modules/modals/CreateTable.vue
  src/modules/modals/EditColumn.vue
  src/modules/modals/EditContext.vue
  src/modules/modals/EditRow.vue
  src/modules/modals/EditTable.vue
  src/modules/modals/FileActionImport.vue
  src/modules/modals/Import.vue
  src/modules/modals/TransferContext.vue
  src/modules/modals/TransferTable.vue
Labels: 4. to release, technical debt

#1328 Fix console warnings and errors
  cypress/e2e/tables-favorite.cy.js
  src/modules/navigation/partials/NavigationTableItem.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/shared/utils/displayError.js
Labels: bug, 3. to review

#787 feat: Use simple input field instead of multiselect for plain URLs
  cypress/e2e/column-text-link.cy.js
  cypress/support/commands.js
  src/modules/sidebar/sections/SidebarIntegration.vue
  src/shared/components/ncTable/partials/rowTypePartials/TextLinkForm.vue
  src/shared/mixins/copyToClipboard.js
Labels: enhancement, design, papercut, 3. to review
