Repository nextcloud/tables, pull requests merged in 2024-02, with the labels that each got.

#811 fix: Properly insert rows into views for the new db structure
  cypress/e2e/view.cy.js
  lib/Service/RowService.php
Labels: bug, 3. to review

#828 fix: Pass all table columns along as we need them for filtering the rows
  lib/Db/Row2Mapper.php
  lib/Service/RowService.php
Labels: bug, 3. to review

#826 fix: properly delete rows in views
  cypress/e2e/view.cy.js
  lib/Service/RowService.php
  src/modules/main/partials/editViewPartials/filter/FilterEntry.vue
  src/modules/main/partials/editViewPartials/filter/FilterForm.vue
  src/modules/main/partials/editViewPartials/filter/FilterGroup.vue
  src/modules/main/sections/DataTable.vue
  src/modules/modals/EditRow.vue
  src/modules/modals/ViewSettings.vue
  src/modules/navigation/partials/NavigationViewItem.vue
  src/shared/components/ncTable/partials/TableRow.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/shared/components/ncTable/sections/Options.vue
Labels: bug, 2. developing

#808 enh: Use table id for events
  src/modules/main/partials/TableView.vue
  src/modules/main/sections/EmptyTable.vue
  src/modules/main/sections/MainWrapper.vue
  src/modules/modals/CreateColumn.vue
  src/modules/modals/CreateRow.vue
  src/modules/modals/DeleteColumn.vue
  src/modules/modals/DeleteRows.vue
  src/modules/modals/EditColumn.vue
  src/modules/modals/EditRow.vue
  src/modules/modals/Modals.vue
  src/modules/modals/TransferTable.vue
  src/shared/components/ncTable/NcTable.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/shared/components/ncTable/sections/Options.vue
Labels: enhancement, 2. developing, feedback-requested

#823 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: dependencies, 3. to review, automated

#786 fix: Make table header sticky
  package-lock.json
  package.json
  src/App.vue
  src/modules/main/sections/Dashboard.vue
  src/modules/main/sections/DataTable.vue
  src/modules/main/sections/ElementDescription.vue
  src/modules/navigation/sections/Navigation.vue
  src/pages/Table.vue
  src/pages/View.vue
  src/shared/components/ncTable/NcTable.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/views/ContentReferenceWidget.vue
Labels: bug, papercut, 3. to review

#846 fix: Only skip failing table data loading instead of full failure
  lib/Db/Row2Mapper.php
  lib/Service/TableService.php
Labels: bug, 3. to review

#841 feat(db): database structure for contexts
  lib/Migration/Version000800Date20240213123743.php
  psalm.xml
Labels: enhancement, 3. to review

#851 fix: Apply fill to path for svg app icon
  img/app.svg
Labels: bug, 3. to review

#853 Fix hide user status from owner avatar (issue #829)
  src/modules/main/sections/Dashboard.vue
  src/modules/main/sections/ElementDescription.vue
  src/modules/navigation/partials/NavigationTableItem.vue
Labels: bug, 3. to review

#825 perf: Optimize lazy imports for reference widgets
  src/reference.js
Labels: 3. to review, performance

#862 fix(DB): type of context_id must be int
  lib/Migration/Version000800Date20240213123743.php
Labels: 3. to review

#843 feat: hold multiple tables/views in global store
  src/modules/main/sections/MainWrapper.vue
  src/modules/modals/CreateColumn.vue
  src/modules/modals/DeleteColumn.vue
  src/modules/modals/DeleteRows.vue
  src/modules/modals/EditColumn.vue
  src/modules/modals/EditRow.vue
  src/modules/modals/Import.vue
  src/shared/components/ncTable/NcTable.vue
  src/shared/components/ncTable/sections/CustomTable.vue
  src/store/data.js
Labels: enhancement, 3. to review

#859 fix: Avoid sql error on postgres
  .github/workflows/integration.yml
  lib/Db/Row2Mapper.php
Labels: bug, 3. to review

#878 node type constants and convenience methods to check access and manage permissions
  lib/AppInfo/Application.php
  lib/Service/PermissionsService.php
Labels: enhancement, 3. to review

#845 feat: implement direct file upload
  appinfo/routes.php
  cypress/e2e/tables-import.cy.js
  lib/Controller/ImportController.php
  lib/Service/ImportService.php
  lib/UploadException.php
  src/modules/modals/Import.vue
Labels: enhancement, 3. to review, import/export

#854 feat: autodetect data type during import
  lib/Service/ColumnService.php
  lib/Service/ImportService.php
Labels: enhancement, 3. to review, import/export

#881 fix: Filter returned entity result by view columns
  lib/Db/Row2.php
  lib/Service/RowService.php
Labels: bug, 3. to review

#886 fix(meta): drop 25 support
  .github/workflows/cypress.yml
  .github/workflows/integration.yml
  appinfo/info.xml
  lib/Service/TableTemplateService.php
Labels: technical debt, 3. to review
