Repository nextcloud/tables, pull requests merged in 2025-04, with the labels that each got.

#1724 fix(UI): fetch avatar correctly by user id
  src/modules/sidebar/partials/ShareList.vue
Labels: bug, 3. to review

#1764 refactor: optimized parseEntities for better efficiency
  lib/Db/Row2Mapper.php
Labels: bug, 3. to review, performance

#1765 fix: avoid marking empty link fields as invalid protocol
  src/shared/components/ncTable/mixins/rowHelper.js
Labels: 3. to review
