Repository nextcloud/tables, pull requests merged in 2025-05, with the labels that each got.

#1752 fix(Permissions): view permissions inherit from table permissions
  lib/Db/TableMapper.php
  lib/Db/ViewMapper.php
  lib/Service/PermissionsService.php
  lib/Service/ViewService.php
  tests/integration/features/APIv1.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, 3. to review

#1806 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/unit/bootstrap.php
Labels: 3. to review

#1810 refactor(Controller): remove private ColumnsController
  appinfo/routes.php
  lib/Controller/Api1Controller.php
  lib/Controller/ColumnController.php
  lib/Service/ColumnService.php
  src/store/data.js
  src/views/SmartPicker.vue
Labels: technical debt, 3. to review

#1808 perf: Parallelize initial requests
  src/App.vue
Labels: bug, 3. to review, performance
