Repository nextcloud/tables, pull requests merged in 2025-07, with the labels that each got.

#1890 ci: update workflows from template
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review

#1892 [stable0.8] refactor: simplify Columns::findAllByTable method
  lib/Analytics/AnalyticsDatasource.php
  lib/Api/V1Api.php
  lib/Command/Clean.php
  lib/Command/TransferLegacyRows.php
  lib/Controller/Api1Controller.php
  lib/Migration/NewDbStructureRepairStep.php
  lib/Service/ColumnService.php
  lib/Service/TableService.php
  lib/Service/ViewService.php
Labels: technical debt, 3. to review

#1899 fix: update table edit functionality and improve element selectors
  cypress/e2e/tables-table.cy.js
  cypress/support/commands.js
  src/modules/modals/EditTable.vue
Labels: 3. to review

#1898 Bump to 1.0.0, drop NC 29 support, bump PHP req to 8.1
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
  .github/workflows/psalm-matrix-custom.yml
  appinfo/info.xml
  composer.json
  composer.lock
  cypress/e2e/ToDo list.json
  lib/Capabilities.php
  lib/Controller/Api1Controller.php
  lib/Controller/ApiColumnsController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/ContextController.php
  lib/ResponseDefinitions.php
  openapi.json
  package-lock.json
  package.json
  psalm.xml
  renovate.json
  src/types/openapi/openapi.ts
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review

#1886 fix: add check for column index existence before processing
  lib/Service/ImportService.php
Labels: feedback-requested

#1936 style: format constructor params import methods and classes
  .github/workflows/app-upgrade-mysql.yml
  lib/Service/ImportService.php
Labels: backport-request, technical debt, 3. to review

#1942 [stable0.7] style: format constructor params import methods and classes
  lib/Service/ImportService.php
Labels: technical debt, 3. to review
