Repository nextcloud/tables, pull requests merged in 2025-03, with the labels that each got.

#1684 enh: escape CSV values
  src/shared/components/ncTable/mixins/exportTableMixin.js
Labels: 3. to review

#1656 enh: Restrict text link protocols
  src/modules/modals/CreateRow.vue
  src/modules/modals/EditRow.vue
  src/shared/components/ncTable/mixins/rowHelper.js
  src/shared/constants.js
Labels: bug, 3. to review

#1696 ci: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/renovate-approve-merge.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review

#1694 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1690 fix: use proper meta column names for sorting
  lib/Db/Row2Mapper.php
Labels: bug, 3. to review

#1689 fix: fix creation failure when using creator filter
  lib/Service/RowService.php
Labels: bug, 4. to release

#1621 enhancement: UI fixes for create/edit row dialogs
  src/modules/modals/CreateRow.vue
  src/shared/components/ncTable/partials/rowTypePartials/RowFormWrapper.vue
Labels: bug, design, 3. to review

#1697 build: revert dependencies to last state with green ci
  .github/workflows/lint-php-cs.yml
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: dependencies, 3. to review
