Repository nextcloud/tables, pull requests merged in 2025-02, with the labels that each got.

#1610 ci: fix integration yaml syntax
  .github/workflows/integration.yml
  tests/integration/features/APIv1.feature
  tests/integration/features/APIv2.feature
Labels: 3. to review, tests

#1612 fix(sort): use addOrderBy for sorting with multiple columns
  lib/Db/Row2Mapper.php
Labels: bug, 3. to review

#1409 fix: Properly create new rows in filtered views
  lib/Db/Column.php
  lib/Db/LegacyRowMapper.php
  lib/Db/Row2.php
  lib/Db/Row2Mapper.php
  lib/Helper/ColumnsHelper.php
  lib/Model/RowDataInput.php
  lib/Service/RowService.php
  tests/integration/features/APIv1.feature
  tests/integration/features/bootstrap/FeatureContext.php
  tests/unit/Service/LegacyRowMapperTest.php
Labels: bug, 3. to review, feature: views

#1545 fix(Import): DateTime import fixes
  lib/Db/Column.php
  lib/Service/ImportService.php
  tests/integration/features/APIv1.feature
  tests/integration/resources/import-from-libreoffice-optional-fields.csv
  tests/integration/resources/import-from-libreoffice-optional-fields.csv.license
Labels: bug, backport-request, 3. to review

#1618 [stable0.8] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1659 build: disable minor+ dep updates on old branches
  renovate.json
Labels: 3. to review

#1660 ci: add summaries for cypress and integration tests
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
Labels: 3. to review

#1658 chore: Revert dependency updates that were merged with red ci
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
  appinfo/info.xml
  composer.json
  composer.lock
  package-lock.json
  package.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: dependencies, 3. to review
