Repository nextcloud/tables, pull requests merged in 2025-01, with the labels that each got.

#1444 fix: use 0 for falsy number progress values during sorting
  src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js
Labels: 3. to review

#1519 ci: Hotfix to make login work as long as we are on older cypress version
  cypress/support/commands.js
Labels: 3. to review

#1463 enh: display error popup when import preview fails
  src/modules/modals/Import.vue
Labels: enhancement, 3. to review

#1434 enh: warn during table manager promotion/demotion
  cypress/support/commands.js
  src/modules/sidebar/partials/ShareList.vue
  src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue
  src/shared/modals/DialogConfirmation.vue
Labels: enhancement, 3. to review

#1526 fix: allow adding meta data columns to views again
  lib/Db/Column.php
  lib/Service/ViewService.php
  tests/integration/features/APIv1.feature
  tests/integration/features/bootstrap/FeatureContext.php
Labels: bug, 3. to review, regression, feature: views

#1465 share with teams
  lib/Capabilities.php
  lib/Constants/ShareReceiverType.php
  lib/Db/LegacyRowMapper.php
  lib/Db/RowCellMapperSuper.php
  lib/Db/Share.php
  lib/Db/ShareMapper.php
  lib/Helper/CircleHelper.php
  lib/Helper/UserHelper.php
  lib/Middleware/PermissionMiddleware.php
  lib/Service/PermissionsService.php
  lib/Service/ShareService.php
  openapi.json
  package-lock.json
  package.json
  src/modules/sidebar/mixins/shareAPI.js
  src/modules/sidebar/partials/ShareForm.vue
  src/modules/sidebar/partials/ShareList.vue
  src/shared/mixins/searchUserGroup.js
  src/shared/mixins/shareTypesMixin.js
  src/shared/modals/DialogConfirmation.vue
  src/types/openapi/openapi.ts
  tests/unit/Service/PermissionsServiceTest.php
Labels: enhancement, 2. developing

#1529 deps: drop support for NC 27 and 28
  .github/workflows/cypress-custom.yml
  .github/workflows/integration.yml
  .github/workflows/psalm-matrix-custom.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  appinfo/info.xml
  cypress/e2e/tables-import.cy.js
  cypress/support/commands.js
Labels: dependencies, 3. to review

#1295 feat: Add UI elements to modify navigation display
  appinfo/routes.php
  cypress/e2e/context.cy.js
  lib/Controller/NavigationController.php
  lib/Db/ContextMapper.php
  lib/Db/ContextNavigationMapper.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Service/ContextService.php
  lib/Service/ShareService.php
  openapi.json
  src/modules/modals/CreateContext.vue
  src/modules/modals/EditContext.vue
  src/modules/navigation/partials/NavigationContextItem.vue
  src/service/rebuild-navigation.js
  src/shared/constants.js
  src/store/store.js
  tests/psalm-baseline.xml
Labels: enhancement, 2. developing

#1525 fix(Views): allow to sort for meta columns
  lib/Service/ViewService.php
Labels: bug, backport-request, 3. to review

#1193 feat(Contexts): enable nav bar display logic
  appinfo/routes.php
  cypress/e2e/context.cy.js
  lib/Controller/NavigationController.php
  lib/Db/ContextMapper.php
  lib/Db/ContextNavigationMapper.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Service/ContextService.php
  lib/Service/ShareService.php
  openapi.json
  src/modules/modals/CreateContext.vue
  src/modules/modals/EditContext.vue
  src/modules/navigation/partials/NavigationContextItem.vue
  src/service/rebuild-navigation.js
  src/shared/constants.js
  src/store/store.js
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review

#1326 feat: add support for teams in usergroup column
  .github/workflows/cypress-custom.yml
  appinfo/info.xml
  cypress/e2e/ToDo list.json
  cypress/e2e/column-usergroup.cy.js
  cypress/support/commands.js
  lib/Controller/Api1Controller.php
  lib/Controller/ApiColumnsController.php
  lib/Controller/ApiTablesController.php
  lib/Controller/ColumnController.php
  lib/Db/Column.php
  lib/Dto/Column.php
  lib/Migration/Version000000Date20210921000000.php
  lib/Migration/Version000800Date20240712000000.php
  lib/Migration/Version000800Date20240828000000.php
  lib/ResponseDefinitions.php
  lib/Service/ColumnService.php
  openapi.json
  src/modules/modals/CreateColumn.vue
  src/shared/components/ncTable/mixins/columnsTypes/usergroup.js
  src/shared/components/ncTable/partials/TableCellUsergroup.vue
  src/shared/components/ncTable/partials/columnTypePartials/forms/UsergroupForm.vue
  src/shared/components/ncTable/partials/rowTypePartials/UsergroupForm.vue
  src/shared/mixins/searchUserGroup.js
  src/types/openapi/openapi.ts
  tests/integration/features/APIv2.feature
Labels: enhancement, 3. to review

#1534 fix(RowMappers): value might at least be null
  lib/Db/RowCellMapperSuper.php
  lib/Db/RowCellSelectionMapper.php
  lib/Db/RowCellUsergroupMapper.php
Labels: bug, 3. to review

#1536 build(release): 0.8.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1537 build(release): 0.9.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1542 fix(Favorites): repair runtime cache population
  lib/Service/FavoritesService.php
Labels: bug, backport-request, 3. to review

#1551 fix: wrap usergroup's cell values
  src/shared/components/ncTable/partials/TableCellUsergroup.vue
Labels: bug

#1557 chore(dev-deps): Bump nextcloud/ocp package
  composer.json
  composer.lock
Labels: bug, 3. to review

#1535 feat(Templates): extend the tutorial table
  cypress/e2e/tables-archive.cy.js
  cypress/e2e/tables-export-csv.cy.js
  cypress/e2e/tables-favorite.cy.js
  cypress/e2e/tables-fe-filters.cy.js
  cypress/e2e/tables-import.cy.js
  cypress/e2e/tables-rows.cy.js
  cypress/support/commands.js
  lib/Service/TableService.php
  lib/Service/TableTemplateService.php
Labels: 3. to review

#1561 deps(PHP): update phpoffice/phpspreadsheet
  composer.lock
Labels: dependencies, 3. to review

#1560 ci(config): stop updates for 0.7, enable PHP updates in renovate
  .github/workflows/npm-audit-fix.yml
  renovate.json
Labels: 4. to release
